In [264]:
import pandas as pd
import numpy as np

In [265]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [266]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [267]:
def relu(x):
    return 0 if x <= 0 else x

In [268]:
input_arr = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target_arr = np.array([[0, 1], [1, 0], [1, 0], [0, 1]])

In [269]:
hidden_neurons = 2
input_neurons = 2
output_neurons = 2
learning_rate = 0.1
epochs = 50000

In [270]:
np.random.seed(42)

#### RANDOM WEIGHTS

In [271]:
w1 = np.random.uniform(-1, 1)
w2 = np.random.uniform(-1, 1)
w3 = np.random.uniform(-1, 1)
w4 = np.random.uniform(-1, 1)

w5 = np.random.uniform(-1, 1)
w6 = np.random.uniform(-1, 1)
w7 = np.random.uniform(-1, 1)
w8 = np.random.uniform(-1, 1)

#### RANDOM BIASES

In [272]:
b1 = np.random.uniform(-1, 1)
b2 = np.random.uniform(-1, 1)

b3 = np.random.uniform(-1, 1)
b4 = np.random.uniform(-1, 1)

In [273]:
for epoch in range(epochs):
    hidden_input_1 = input_arr[:, 0] * w1 + input_arr[:, 1] * w2 + b1
    hidden_input_2 = input_arr[:, 0] * w3 + input_arr[:, 1] * w4 + b2

    hidden_output_1 = sigmoid(hidden_input_1)
    hidden_output_2 = sigmoid(hidden_input_2)

    output_input_1 = hidden_output_1 * w5 + hidden_output_2 * w6 +  b3
    output_input_2 = hidden_output_1 * w7 + hidden_output_2 * w8 + b4

    output_1 = sigmoid(output_input_1)
    output_2 = sigmoid(output_input_2)

    output = np.vstack([output_1, output_2]).T

    error = target_arr - output
    MSE = np.mean(np.square(error))

    d_output_1 = error[:, 0] * sigmoid_derivative(output_1)
    d_output_2 = error[:, 1] * sigmoid_derivative(output_2)

    d_hidden_output_1 = d_output_1 * w5 + d_output_2 * w7
    d_hidden_output_2 = d_output_1 * w6 + d_output_2 * w8

    d_hidden_1 = d_hidden_output_1 * sigmoid_derivative(hidden_output_1)
    d_hidden_2 = d_hidden_output_2 * sigmoid_derivative(hidden_output_2)

    w1 += learning_rate * np.sum(d_hidden_1 * input_arr[:, 0])
    w2 += learning_rate * np.sum(d_hidden_1 * input_arr[:, 1])
    w3 += learning_rate * np.sum(d_hidden_2 * input_arr[:, 0])
    w4 += learning_rate * np.sum(d_hidden_2 * input_arr[:, 1])

    w5 += learning_rate * np.sum(d_output_1 * hidden_output_1)
    w6 += learning_rate * np.sum(d_output_1 * hidden_output_2)
    w7 += learning_rate * np.sum(d_output_2 * hidden_output_1)
    w8 += learning_rate * np.sum(d_output_2 * hidden_output_2)

    if epoch % 100 == 0:
        print(f"Epoch {epoch % 10000} | MSE: {MSE}")

Epoch 0 | MSE: 0.33825213731370185
Epoch 100 | MSE: 0.25748672783805493
Epoch 200 | MSE: 0.25045899775639024
Epoch 300 | MSE: 0.24952401063983706
Epoch 400 | MSE: 0.248527204246695
Epoch 500 | MSE: 0.24715615107816918
Epoch 600 | MSE: 0.24521310987727601
Epoch 700 | MSE: 0.24263609783157447
Epoch 800 | MSE: 0.23953185883340108
Epoch 900 | MSE: 0.23608961510447599
Epoch 1000 | MSE: 0.23247869417995037
Epoch 1100 | MSE: 0.22881071807306091
Epoch 1200 | MSE: 0.22514731631272844
Epoch 1300 | MSE: 0.22151889886343604
Epoch 1400 | MSE: 0.21794069477119027
Epoch 1500 | MSE: 0.21442273757386868
Epoch 1600 | MSE: 0.210973731380503
Epoch 1700 | MSE: 0.20760106220006735
Epoch 1800 | MSE: 0.2043099943334572
Epoch 1900 | MSE: 0.20110375339363085
Epoch 2000 | MSE: 0.19798450543388268
Epoch 2100 | MSE: 0.19495455758744118
Epoch 2200 | MSE: 0.19201722314705033
Epoch 2300 | MSE: 0.18917706310175383
Epoch 2400 | MSE: 0.1864393964664769
Epoch 2500 | MSE: 0.18380913271301685
Epoch 2600 | MSE: 0.1812891691

In [274]:
print(f"Final Output: \n{output}\n")
print(f"Final Output Rounded: \n{np.round(output)}")

Final Output: 
[[0.01601988 0.98403795]
 [0.85560977 0.14381642]
 [0.85560939 0.14381681]
 [0.20561169 0.79524778]]

Final Output Rounded: 
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


## USING KERAS AND TENSORFLOW

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

data = pd.read_csv("Experiment3.csv")
input_arr = data[['X1', 'X2']].values

output_arr = data[['O1', 'O2']].values

model = keras.Sequential([
    layers.Dense(2, input_dim=2, activation='relu'), 
    layers.Dense(2, activation='relu'),              
    layers.Dense(2, activation='sigmoid')            
])

model.compile(optimizer=keras.optimizers.Adam(),
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(input_arr, output_arr, epochs=10000, verbose=1)

print("\nFinal Evaluation:")
model.evaluate(input_arr, output_arr)

print("\nPredictions:")
predictions = model.predict(input_arr)
print(predictions)

print("\nRounded Output:")
print(np.round(predictions))


/home/sameer42/anaconda3/envs/gpu-env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)



Final Evaluation:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.4774

Predictions:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[3.3335617e-01 6.6666359e-01]
 [3.3335617e-01 6.6666359e-01]
 [9.9993140e-01 9.2234968e-06]
 [3.3335617e-01 6.6666359e-01]]

Rounded Output:
[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]
