## SOM

In [ ]:
# A2 batch wala

import numpy as np

inputs = np.array([
    [1, 0, 1, 0],  
    [1, 0, 0, 0],  
    [0, 0, 0, 1],  
    [0, 1, 0, 1]   
])

weights = np.array([
    [0.2, 0.6, 0.5, 0.9], 
    [0.8, 0.4, 0.7, 0.3]   
])

learning_rate = 0.6

def euclidean_distance(x, w):
    return np.linalg.norm(x - w)

print("Initial Weights:")
print(weights)

for i, x in enumerate(inputs):
    print(f"\nInput X{i+1}: {x}")

    distances = np.array([euclidean_distance(x, w) for w in weights])
    print(f"Distances: {distances}")

    bmu_index = np.argmin(distances)
    print(f"BMU: y{bmu_index+1}")

    weights[bmu_index] += learning_rate * (x - weights[bmu_index])
    print(f"Updated weights for y{bmu_index+1}: {weights[bmu_index]}")

learning_rate *= 0.5
print("\nWeights after 1 epoch:")
print(weights)
print(f"New learning rate: {learning_rate}")


Initial Weights:
[[0.2 0.6 0.5 0.9]
 [0.8 0.4 0.7 0.3]]

Input X1: [1 0 1 0]
Distances: [1.43527001 0.6164414 ]
BMU: y2
Updated weights for y2: [0.92 0.16 0.88 0.12]

Input X2: [1 0 0 0]
Distances: [1.43527001 0.90598013]
BMU: y2
Updated weights for y2: [0.968 0.064 0.352 0.048]

Input X3: [0 0 0 1]
Distances: [0.81240384 1.40403989]
BMU: y1
Updated weights for y1: [0.08 0.24 0.2  0.96]

Input X4: [0 1 0 1]
Distances: [0.7909488  1.68621707]
BMU: y1
Updated weights for y1: [0.032 0.696 0.08  0.984]

Weights after 1 epoch:
[[0.032 0.696 0.08  0.984]
 [0.968 0.064 0.352 0.048]]
New learning rate: 0.3


In [10]:
# A1 batch wala

import numpy as np

inputs = np.array([
    [0.4,0.07]  
])

weights = np.array([
    [0.7,0.5], 
    [0.3,0.2], 
    [0.1,0.4], 
    [0.6,0.9], 
    [0.1,0.5]
])

learning_rate = 0.3

def euclidean_distance(x, w):
    return np.linalg.norm(x - w)

print("Initial Weights:")
print(weights)

for i, x in enumerate(inputs):
    print(f"\nInput X{i+1}: {x}")

    distances = np.array([euclidean_distance(x, w) for w in weights])
    print(f"Distances: {distances}")

    bmu_index = np.argmin(distances)
    print(f"BMU: y{bmu_index+1}")

    weights[bmu_index] += learning_rate * (x - weights[bmu_index])
    print(f"Updated weights for y{bmu_index+1}: {weights[bmu_index]}")

learning_rate *= 0.5
print("\nWeights after 1 epoch:")
print(weights)
print(f"New learning rate: {learning_rate}")


Initial Weights:
[[0.7 0.5]
 [0.3 0.2]
 [0.1 0.4]
 [0.6 0.9]
 [0.1 0.5]]

Input X1: [0.4  0.07]
Distances: [0.52430907 0.16401219 0.44598206 0.85375641 0.52430907]
BMU: y2
Updated weights for y2: [0.33  0.161]

Weights after 1 epoch:
[[0.7   0.5  ]
 [0.33  0.161]
 [0.1   0.4  ]
 [0.6   0.9  ]
 [0.1   0.5  ]]
New learning rate: 0.15
